# Generated by Django 3.2.7 on 2022-03-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField()),
                ('chartsheetdate', models.DateField()),
                ('caseno', models.CharField(default=False, max_length=100)),
                ('caseyear', models.IntegerField()),
                ('casetype', models.CharField(max_length=100)),
                ('casest', models.CharField(max_length=10000)),
            ],
        ),
    ]
