# Generated by Django 3.2.7 on 2022-03-07 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_case_caseno'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='gravity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='case',
            name='last_hearing_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
