# Generated by Django 3.2.7 on 2022-03-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_case_gravity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='caseno',
            new_name='case_No',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='casest',
            new_name='case_statement',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='casetype',
            new_name='case_type',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='chartsheetdate',
            new_name='chart_sheet_filling_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='caseyear',
        ),
    ]
